### ISSUE TITLE
Implement file upload functions? 

### ISSUE THREAD

**Issue by mywarr** [miki2826/botly#16]
Do you have plan implementing file upload functions?
For now it only accept attachment from payload. 
it would be great if botly can upload attachment from local files or streaming from other libs such as  node-webshot.

```curl
curl  \
  -F recipient='{"id":"USER_ID"}' \
  -F message='{"attachment":{"type":"file", "payload":{}}}' \
  -F filedata=@/tmp/receipt.pdf \
  "https://graph.facebook.com/v2.6/me/messages?access_token=PAGE_ACCESS_TOKEN" 
```

**Comment by miki2826** [comment]
added in 730318e
