### ISSUE TITLE
Mandatory TypeScript Question

### ISSUE THREAD

**Issue by nevi-me** [miki2826/botly#17]
Hey, came across this today when searching NPM, I'm going to give botly a try. Do you have plans of supporting TypeScript? I think the FB Messenger API is simple enough not to need it, but just asking in case there are some plans to.

**Comment by miki2826** [comment]
Hi @nevi-me
There is no plan currently to support typescript in botly. 
That being said, I agree some developers would like to get typescript definitions and I have no objections to add it. Feel free to contribute if you like. 

Thank,
Miki
