### ISSUE TITLE
Unable to setup setGreetingText.

### ISSUE THREAD

**Issue by XavierColombel** [miki2826/botly#18]
I put PageID in a variable, then here is my code:

```
botly.setGreetingText({
    pageId: fb_page_id,
    "greeting":[
        {
        "locale":"default",
        "text":"Hello!"
        }, {
        "locale":"en_us",
        "text":"Timeless apparel for the masses."
        }
    ]}, (err, body) => {
    //log it
});
```

Any help would be really appreciated. Thanks.

**Comment by jsappme** [comment]
any update on this?

**Comment by miki2826** [comment]
It seems to be working for me:
![img_1035](https://cloud.githubusercontent.com/assets/5138735/24033553/2a24415e-0af6-11e7-9393-c65827e7f20f.png)

@XavierColombel Are you getting any error in the callback?

**Comment by jsappme** [comment]
@miki2826 can you share your code?

**Comment by miki2826** [comment]
@jsappme
I copy pasted the same code provided here and added it to the example.

**Comment by jsappme** [comment]
here is my code:

```
bot.setGreetingText({
    pageId: config.facebook.pageId,
    "greeting":[
        {
        "locale":"default",
        "text":"Hello!"
        }, {
        "locale":"en_us",
        "text":"Timeless apparel for the masses."
        }
    ]
  }, (err, body) => {
  console.log("GREETING: " + JSON.stringify(err))
  console.log("GREETING: " + JSON.stringify(body))
})
```

Result:
GREETING null
GREETING {"result":"success"}

But no greeting shown

**Comment by miki2826** [comment]
The greeting is shown only for new conversations. Try deleting your current conversation and starting a new one.

**Comment by jsappme** [comment]
I did and nothing

**Comment by XavierColombel** [comment]
Here is my code and, even after deleting conversations, nothing shows.

```
botly.setGreetingText({
    pageId: fb_page_id,
    "greeting":[
        {
            "locale":"default",
            "text":"Hello {{user_first_name}}!"
        }
    ]}, (err, body) => {
        console.log("greeting", body);
});
```

**Comment by miki2826** [comment]
Are you trying it on desktop or on mobile?
I did encounter a few times where Facebook didn't show the greetings in desktop but did in mobile.

**Comment by XavierColombel** [comment]
Mobile

**Comment by miki2826** [comment]
No idea...
If there was an issue with the structure Facebook would have returned an error. 
Also, same code worked for me.

**Comment by XavierColombel** [comment]
Weird. 😓

**Comment by XavierColombel** [comment]
I just changed the callback URL (ngrok) and it works now. Really weird.
