### ISSUE TITLE
Advice for keeping the templates in different modules ? 

### ISSUE THREAD

**Issue by cAstraea** [miki2826/botly#25]
Was thinking how to better organise  my code and keep the menus in different files so I don't clutter the main app.js I can require but not sure how to go about it since they require lots of information from the main app.js  ? Anyone got an example ? 
Should I pass everything I need to  return mainMenu(); ? like return  mainMenu(botly,Botly,sender) ?

**Comment by miki2826** [comment]
@cAstraea can you please provide an example of what you currently have?
