### ISSUE TITLE
 X-Hub-Signature configuration missing

### ISSUE THREAD

**Issue by chosa91** [miki2826/botly#26]
Hi, 
I miss the configuration for custom and pre-configurable headers like [X-Hub-Signature](https://developers.facebook.com/docs/graph-api/webhooks).

`The HTTP request will contain an X-Hub-Signature header which contains the SHA1 signature of the request payload, using the app secret as the key, and prefixed with sha1=. Your callback endpoint can verify this signature to validate the integrity and origin of the payload`

**Comment by marjanSterjev** [comment]
Hi,

Maybe this article can help you with the implementation:

https://www.linkedin.com/pulse/facebook-chatbot-webhook-identify-your-caller-marjan-sterjev/

Best Regards,

Marjan
