### ISSUE TITLE
How do we set sender actions?

### ISSUE THREAD

**Issue by sidkoth1996** [miki2826/botly#36]
Hello, this is my first bot and I would like to provide a typing indicator to allow users to see whether the message they sent is being processed or not.

I took a look at the Facebook Send API reference and wrote the following code:

`botly.send({recipient: {id: senderId}, sender_action: "typing_on"}, function(err, data) {
		console.log(data);
	});`

I am getting the following console output: 

`{ error: 
   { message: '(#100) Must send either message or state',
     type: 'OAuthException',
     code: 100,
     error_subcode: 2018015,
     fbtrace_id: 'H1BxIEyCbKk' } }`

Any help with this will be immensely appreciated. Thank you!

**Comment by aellanglet** [comment]
`botly.sendAction({
       id: senderId,
       action: Botly.CONST.ACTION_TYPES.TYPING_ON
     });

     botly.sendText({
       id: senderId,
       text: 'Hi !'
     }`

It will send the typing_on action until your bot send the text. :) At least it's what it does for me !
For this exemple you will not see very much but with a carousel it work well.
