### ISSUE TITLE
message after postback.?

### ISSUE THREAD

**Issue by sushantshekhar20** [miki2826/botly#37]
In Short.. I am trying to save(in var) a message user sends me after a payload.

Longer Version..
Suppose a user clicks on the menu where he is supposed to tell me his/her phone number.
I get a payload "send_number"
Now i want to save the number to a variable.

How do i do this?
the message event takes in any message !```

botly.on("message", (sender, message, data) => {

});
```

**Comment by aellanglet** [comment]
you can pass the var in the payload and trigger it by a RegExp or something else to check the words, i've done something similar to save favorites recipe that i send with a carousel. I passed it in my payload, exemple of what i've done :
`let buttonAdd = {
                  "type": "postback",
                  "title": "Add favorites",
                  "payload": "{\"ACTION\":\"ADD_FAVORITES\",\"ID_RECIPE\":\"" + document.ID + "\"}"
                };`

next, in the postback check i do : 
`if (postback.indexOf("ADD_FAVORITES") != -1) {
let ID_RECIPE = JSON.parse(postback).ID_RECIPE;
}`

what you will get is the document.ID that you passed, you can do at least a 1000 chars string if i remember well.

For your issue, i don't understand how you can't just save the number into a var (data.text show what the user send) but you can maybe send a button like this after the user send the number, you will store it and be able to use it.
I advice you to use a DB like mongo and store things like that by fb_id, maybe it will be more easier ;)

Hope it helps you... 👍

**Comment by aellanglet** [comment]
OK i understand what you wanted to do, i find the answer unfortunately : https://stackoverflow.com/questions/37142978/waiting-for-a-text-reply-with-a-facebook-messenger-bot

So you have to do some compare like "if (data.text == ....)" with some regex or something, seems there is no really answer for the moment :s

**Comment by sushantshekhar20** [comment]
Thanks!
